apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - git@github.com:amazingandyyy/renovate-source?ref=v1.3.0

configMapGenerator:
  - name: app
    behavior: merge
    literals:
      - KEY2=value2
